# Site settings
email: kevin@greenisms.com
baseurl: "www.greenisms.com"
paginate: 5
paginate_path: "/blog/page-:num"
google_analytics: UA-91235140-1

# SEO settings
title: Greenisms
description: Quality Content, Sourced Responsibly, Designed to Help You!
url: ""
twitter_username: 
default_img: 

# Profile settings
name: 
profile_img: 
profile: 
social:

# Build settings
include: ["_categories"]
exclude: ["_screenshots", "Gemfile", "Gemfile.lock"]
markdown: kramdown
permalink: /:year/:month/:day/:title/

# Sass
sass:
  style: compressed

# Gems
gems: [jekyll-paginate, jekyll-sitemap, octopress-autoprefixer]
